# author Junji Takakura <j.takakura@gmail.com>

name: spine_flutter
description: The spine-flutter runtime provides functionality to load and manipulate Spine skeletal animation data using Flutter.
version: 0.1.1
homepage: https://github.com/jtakakura/spine_flutter/

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  fimber: ^0.6.4
  flutter:
    sdk: flutter
  spine_core: ^0.3.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
