# author Junji Takakura <j.takakura@gmail.com>

name: spine_flutter
description: The spine-flutter runtime provides functionality to load and manipulate Spine skeletal animation data using Flutter.
version: 0.1.1
homepage: https://github.com/jtakakura/spine_flutter/

environment:
  flutter: '>=2.10.0 <3.0.0'
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #spine_core: ^0.3.1
  spine_core:
    path: ../spine_core
    #git: https://github.com/signmotion/spine_core.git

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
